### ISSUE TITLE
BUG: Performance issue while dragging component to canvas when you have 2k component on canvas

### ISSUE THREAD

**Issue by mohdSuhailCoditation** [GrapesJS/grapesjs#4323]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Google Chrome Version 101.0.4951.41 (Official Build) (64-bit)

### Reproducible demo link

https://jsfiddle.net/Laze0pyg/

### Describe the bug

**How to reproduce the bug?**
1. Add 2k components using the below script.
2. `for(let i = 0;i<2000;i++)
    editor.addComponents('<div>ABC</div>');`
3. Try dragging Text Block on to the canvas.

**What is the expected behavior?**
There should be no lag.

**What is the current behavior?**
The green line placeholder is lagging

**JS Fiddle**
https://jsfiddle.net/Laze0pyg/

**Demo**

https://user-images.githubusercontent.com/100282281/168098195-9b69c333-df8b-43e0-bd64-4f7bee004b48.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
Yeah @GedMarc you're right but IMHO the Sorter could be definitely improved in such a case. Right now when the pointer goes over the component (eg. body) the Sorter calculates the dimensions and computed styles of all the children so I can see here a space for improvements.
Unfortunately, I don't have any ETA for such improvement, so if anybody wants to explore this path, PRs are welcome.

**Comment by artf** [comment]
> But then when will it be enough? Slow down at 2k, then next someone report 3k, 5k, 10k, or more ...

Yeah I mean, the idea is if the HTML page itself is laggy (ml of DOM elements with styles and stuff) there is no point in improving as the editor preview should more or less show what you'd see outside of the editor.
But in the case of the demo, you can see how the lag starts only when you activate the component sorter, so that's why I see think there is room for improvements.

**Comment by mohdSuhailCoditation** [comment]
Thanks @artf. I am happy to explore optimisation of sorter.js. It would be really helpful if you could provide some high level pointers and approach for the same.

**Comment by lexoyo** [comment]
Hi that would be great to optimize this :+1:

I would suggest to use the browser's performance tool, but you probably know this

Thank you for looking into this @mohdSuhailCoditation

**Comment by bgrand-ch** [comment]
@artf Does GrapesJS use Web Workers or virtual scrolling to optimise the rendering of a list of components or for large component (lot's of content with lot's of places taken? 🤔

**Comment by vizardkill** [comment]
https://github.com/GrapesJS/grapesjs/assets/37307788/2d653d49-1a57-458c-bc8c-4833c8c7a690


I have the same problem, and I don't think it is due to the size, I am using the pageManager and I preload an html template and trying to drag new elements to the canvas it happens that the canvas only inserts the component after 10 seconds, it even freezes momentarily

**Comment by bgrand-ch** [comment]
Hello, I think it would be interesting (but certainly very complex) to implement the following solution:

Load and display components in "virtual scrolling" mode.

If there are no components displayed, display the first X components and pre-load (retrieve, parse, etc.) the next X components in the background.

When scrolling down, display the X pre-loaded components and pre-load the next X components in the background. Remove the first X components when scrolling down.

When scrolling up, do the same procedure, but in reverse. Display the previous X components and remove the last X components when scrolling up.

@artf What do you think?

**Comment by artf** [comment]
@vizardkill are you able to create a reproducible demo? Does it happen with all components?

@bgrand-ch Virtualizing the dom makes sense with stuff like a list of items, usually when the size of a single item is known in advance and it's static. Such an approach couldn't work with a generic HTML page where stuff could change the size (eg. JS/CSS) and you might lose the sync with the scrollbar, otherwise, browsers would do such optimization natively.

**Comment by bgrand-ch** [comment]
@artf As a workaround, I was thinking of preserving the height and the scroll bar by leaving a "placeholder" (an empty div), which is the size of the removed content. 🤔

**Comment by MrVibe** [comment]
I am facing the exact same issue as described by @vizardkill  : https://jumpshare.com/v/Dbsty6qTv5cRXPyJKGfX
The reason might be very well connected to the number of items on the page or we are doing the same mistake.

**Comment by artf** [comment]
With the latest release, containing the refactor of the Sorter by @mohamedsalem401, the previous demo seems to be working fine now 🥳

**Comment by bgrand-ch** [comment]
ℹ @artf Hello, I'm having performance problems with a large document built with GrapesJS (+80 pages once exported as a PDF).

I found the following article, are these various optimisations already implemented in GrapesJS?
https://onenine.com/ultimate-guide-to-backbonejs-performance-optimization/

There's also this CSS property that seems very simple to optimise the paint of HTML elements:
https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility

Have a nice day.
