### ISSUE TITLE
BUG: Missing inline styles used by CKEditor when adding raw html components 

### ISSUE THREAD

**Issue by gustavohleal** [GrapesJS/grapesjs#4503]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chromium v96

### Reproducible demo link

https://grapesjs.com/demo-newsletter-editor.html

### Describe the bug

**How to reproduce the bug?**
1. Open the developer tools at the console tab
2. Run the code below
3. Select the text added
4. Edit something with CKEditor
5. Select another component

**What is the expected behavior?**
Expected to add inline styles from the spans inside the text component so that the CKEditor understand the text-styling and keep them when opened.

**What is the current behavior?**
Adding the raw HTML by `editor.addComponent()` do add the styling, but once you edit the text and blur it the style is removed from the text segments where they belong. This happens only with CKEditor because it uses the `<span>` and inline style to edit the text.
I'm putting the newsletter preset demo because it is the only demo from grapesjs that use CKEditor.
If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
editor.DomComponents.clear()
editor.addComponents(`<div data-gjs-type="text"><span style="color: blue;">Teste</span> de <span style="font-family: arial; font-size: 25px"><b>span</b></span> inline</div>`)

```
I need to add components this way so that legacy HTML models and templates can be opened into grapesjs. Sometimes CKEditor even does not recognizes that `spans` or `<b>` elements are text segments and throw an error as it does not work with  those text styling elements.
This problem is similar to #3069 that was fixed and I believe this has returned once the feature of transforming inline styles into classes was added. 
Can we somehow keep the elements inside text components as raw html?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shkhalid** [comment]
+1

**Comment by pety-dc** [comment]
Hey
I've been having similar issues. I think it's quite serious as both newsletter and mjml demo are affected. (Both use CKeditor as RTE)

When I import a content that has a text (mj-text) that has styled elements (span) the imported content gets parsed and the styling elements are recognized as individual components and not as contents of the wrapping text element.


example (This is valid according to mjml.io):
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>
        <mj-divider border-color="#F45E43"></mj-divider>
        <mj-text font-size="20px" font-family="helvetica"><strong>Hello</strong> <span style="color: #F45E43;">World</span></mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

Expected result:
![image](https://user-images.githubusercontent.com/25766885/230409523-b8b576bb-d96e-4ef6-914d-45628bf20474.png)


Result:
![image](https://user-images.githubusercontent.com/25766885/230409268-74dd3982-23f8-4439-ba5c-1980eb9ec508.png)


The problem is that due to nested texts are parsed into components, their style attributes gets stripped and the result code does't contain it anymore:
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-image width="100px" src="/assets/img/logo-small.png">
        </mj-image>
        <mj-divider border-color="#F45E43">
        </mj-divider>
        <mj-text font-size="20px" font-family="helvetica">
          <strong>Hello</strong> 
          <span id="io1ak">World</span>
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

The style must be there under the hood somewhere. Because when I doubleclick on the text, the CKEditor loads and somehow "restores" the style attribute. But unless I open every text for editing on each content edit, the style gets lost.

Not all GrapesJS versions are affected. 
`0.21.1`, and `0.21.1` are
But `0.16.3` - `0.19.5` behaves as expected.


I checked changes from `0.19.5` to `0.20.1` and I couldn't clearly trace back what could have casued the change in this behaviour. But probably has something to do with `Support textable for extended Text components`

Now I know that nested texts are native to grapesJS, since this is the default way of styling them. 
But is there a way to disable nested text feature?

**Comment by raymondmakz** [comment]
ckeditor output:
`<div>some rich text from <span style="color:blue">ckeditor</span></div>`
after parsing into editor, become like:
`<div data-gjs-type="text">some rich text from <span style="color:blue" data-gjs-type="default">ckeditor</span></div>`
Basically every dom become components.

Maybe give a choice to developer to decide whether a component should stop add child nodes as components.
Can add a new flag property in component's model, eg: '`stopProcessChildren`'

Inside ./parser/mode/ParserHtml.ts::parseNode() function,
right before going into the recurisve parseNode() and assigning child components
`model.components = this.parseNode(node, {/*...*/});`
- Add an else-if condition: if model's '`stopProcessChildren`' is true, do not do the parseNode() on children nodes. 
- next, need to set the current dom node's innerHtml to model's '`content`' or do this in component definition

From the default ./dom_components/model/Component.ts::toHTML() and ./dom_components/model/Component.ts::getInnerHTML(),
the html output should return model's '`content`' if there are no child components.

Proposed component definition can be like:
```
editor.DomComponents.addType('my-rich-text', {
  isComponent: el => {
    if (allChildText(el)) {  //check if all text node or tagname in textTags
      return { 
		type: 'my-rich-text',	// or can do 'text' here? not sure.
		editable: true,
		content: el.innerHtml,
		components: false,
		stopProcessChildren: true,		//new property
	  };
    }
  },
  // ...
});
```

Concerns: XXS

**Comment by pety-dc** [comment]
Last time I said that based on available web.archive versions previous versions of `0.16.3` - `0.19.5` worked properly
The funny thing is that I tried downgrading grapesJS to any of those versions and I didn't experience any change in my implementation. 

Then I began rolling back the grapesjs-mjml plugin version until 0.5.8 when I finally found a version that somehow works as I expect. (doesn't dive into text components)
I don't quite know the reasons since judging by my inexperienced eyes grapesjs-mjml did not change much between `0.5.8` and `0.6.0`. Yet still that's the case.



@raymondmakz 
Thanks for your proposal.

A `stopProcessChildren` model property that would prevent a componenents contents from further parsing may work. 
I would imagine that this feature should not only work for custom text components, but CKEditor plugin should naturally override that base Text component to prevent grapesJS from taking control over html elements CKEditor uses for formatting.

**Comment by pety-dc** [comment]
Hey @artf 

Thanks for your reply. 

I'm not an expert on XSS vulnerabilities so could you please explain the nagure of the XSS vulnerability not parsing text contents would introduce? Would it make the GrapesJS editor vulnerable for "trojan horse" third party scripts embeded in texts  or the final location of the edited content? 

I'm not arguing, I just wish to better understand your concerns.

Maybe it would be enough to prevent XSS if the content of a text components doesn't get parsed for nested components but <script> tags of any sort get stripped from its content?

**Comment by artf** [comment]
Hey @pety-dc what you're describing is correct. I actually realised that we were already cleaning the HTML from unsafe content during the `parse` but I still preferred to add `disableTextInnerChilds` option for more granular conditions (available in the [new release](https://github.com/GrapesJS/grapesjs/releases/tag/v0.21.2)).

The problem with styles mentioned in this issue was also fixed (not reproducible anymore on the demo) so we can finally close this one. 
Soon I'll also update the CKEditor plugin to fix other issues there.

**Comment by pety-dc** [comment]
Hey @artf 

Sounds good!!!

I've just tested the new solution on the grapesJS-MJML demo which shows that it uses the new `v0.21.2` version.
The option you've introduced is not on by default but I managed to turn it on with the following console command:
`grapesjs.editors[0].Components.config.disableTextInnerChilds = true`

After that the following mjml code which I had previously been using for testing resulted that the embedded text components are no longer selectable in deed.

```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>
        <mj-divider border-color="#F45E43"></mj-divider>
        <mj-text font-size="20px" font-family="helvetica"><strong>Hello</strong> <span style="color: #F45E43;">World</span></mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

All seems fine on the canvas
![image](https://github.com/GrapesJS/grapesjs/assets/25766885/cd0093b9-200f-4d70-9789-74979301b1f7)


But unfortunately despite my expectations that the inner contents should be left rather 'untouched', a `style` attribute on the span still gets stripped. On the canvas it seems ok, but in the source viewer I get this transformed result, which lacks the style on the span.

```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-image width="100px" src="/assets/img/logo-small.png">
        </mj-image>
        <mj-divider border-color="#F45E43">
        </mj-divider>
        <mj-text font-size="20px" font-family="helvetica">
          <strong>Hello</strong> 
          <span id="i0fof">World</span>
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

I found no other trace of the use of `disableTextInnerChilds` setting other than in the `CompontentText.ts` 

How come we got different results regarding the style attributes?

**Comment by artf** [comment]
sorry @pety-dc I missed your reply. 
Anyway, this looks like a core issue as mjml plugin uses `avoidInlineStyle: false` by default so, I'd not expect the style to be stripped, I'll check it later.

**Comment by bhuthardik333** [comment]
@artf - Any update on this issue? If I am going to use `avoidInlineStyle: false` then it will break the media css and it will not work with media. Is there any option using which we can achieve both?
