### ISSUE TITLE
BUG: a tag inside button is removed

### ISSUE THREAD

**Issue by handhikadj** [GrapesJS/grapesjs#4929]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome Latest

### Reproducible demo link

https://codesandbox.io/s/interesting-bell-xntbtr

### Describe the bug

**How to reproduce the bug?**
1. go to the codesandbox
2. drag and drop Custom Code block.
3. put this code inside the Custom Code editor and click Save:
```html
<button class="btn bg-primary text-white">
<a href="https://www.example.com/" target="_blank">Click me</a>
</button>
```
4. Click the button.
5. The button should open the href link when you click it but it's not. Noticed that the a tag is removed inside the button tag

**What is the expected behavior?**
`<a>` tag is not removed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This happens because of the [button implementation](https://github.com/GrapesJS/components-forms/blob/6a63e9edb7b085790e90e98acf54accc5f4bd642/src/components.ts#L260) in the [forms plugin](https://github.com/GrapesJS/components-forms), which allows only textnodes as children. 

If you remove the form plugin you'll be able to see the `<a>` element (if you prefer you can also extend the button component with your own logic).

**Comment by handhikadj** [comment]
so what is the code of "normal" implementation of the button?
btw, may I know why do you make the button to behave like that on the forms plugin?

**Comment by artf** [comment]
If I recall properly the main reason there was a problem with inline text editing with button elements, so that approach was the easiest way to fix a common issue. 
I guess the "normal" implementation would be to skip/overwrite the `init` method but you should think on how to properly handle the  inline text editing.
