### ISSUE TITLE
BUG: draggable/droppable property functions not called while dragging

### ISSUE THREAD

**Issue by rozek** [GrapesJS/grapesjs#5362]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Version 1.56.20 Chromium: 115.0.5790.171 (Offizieller Build) (arm64)

### Reproducible demo link

none

### Describe the bug

I've defined my own component types with type specific drag-and-drop rules:

```
        model: {
          defaults: {
            draggable: function (Candidate) {
console.log('WebCard target candidate',Candidate)
              ...
            },
            droppable: function (Candidate) {
console.log('WebCard drop candidate',Candidate)
              ...
            },
```

but the configured functions are never invoked. Instead, dragging works without any constraints and dropping works into the wrapper element only.

A potentially important detail: my `dragMode` is set to `'absolute'`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rozek** [comment]
even with `draggable` and `droppable` set to `true`, I cannot drag one element into another

**Comment by rozek** [comment]
A first workaround which helps dropping components into other components:
 
1. remove `dragMode:'absolute',` from `grapesjs.init({...})`
2. instead, add `dmode:'absolute',` to `model.defaults` of every component type you want to be draggable (and, perhaps, droppable)

However, the `draggable` and `droppable` functions still do not get called.

**Comment by artf** [comment]
In absolute mode, there is no concept of moving components inside/outside of other components. A component in absolute mode is only updated in style position, it's not moved in the DOM, that's why draggable/droppable does not make sense to work here.

Please @rozek avoid opening BUG issues if you don't have a full understanding of how things are supposed to be working, use Discussions for that matter.
