### ISSUE TITLE
BUG: Error: node_modules/grapesjs/dist/index.d.ts:12551:2 - error TS1005: '?' expected.  12551 }> ? C : {}) | undefined) => (editor: Editor) => void;        ~   Error: node_modules/grapesjs/dist/index.d.ts:12558:3 - error TS1005: '?' expected.  12558  }> ? C : {}) | undefined) => (editor: Editor) => void;

### ISSUE THREAD

**Issue by Akkiiiiiii** [GrapesJS/grapesjs#5377]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Describe the bug

After Upgrade new version 0.21.5 getting these errors . we are working with grapesjs + angular, grapesjs v 0.21.5 not available in both jsFiddle and codeSandbox right now so i'm putting a dummy link. please help us out.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Akkiiiiiii** [comment]
@artf  can you please check this one

**Comment by THEWebDegenerate** [comment]
I use safari  and chrome

**Comment by filipRisteski** [comment]
+1 after upgrade

**Comment by artf** [comment]
I don't see any issue for those lines on my side (`typescript@5.2.2`)
<img width="667" alt="Screenshot 2023-09-16 at 11 12 05" src="https://github.com/GrapesJS/grapesjs/assets/11614725/943eb12d-5d0e-4195-9b77-16136085c16d">

I guess that might related to your local typescript version, otherwise `"skipLibCheck": true` might also be a good workaround.
