### ISSUE TITLE
BUG: When inserting text when component not synced, the text is overwritten from the existing model

### ISSUE THREAD

**Issue by Wayne-Mather** [GrapesJS/grapesjs#5650]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Edge 121.0.2277.83, Firefox 122

### Reproducible demo link

https://jsfiddle.net/50mga1t7/1/

### Describe the bug

**How to reproduce the bug?**
1. Create a toolbar action to insert some text
2. Edit a text node and insert some text
3. Click the toolbar command to insert some new component/text
4. The textnode will reset to the model details before the edit's took place

**What is the expected behavior?**
The textnode should show the current text as being edited and the new inserted text

**What is the current behavior?**
The new text is inserted using the text from the model rather than the current view

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
This is not a bug, merging the current DOM with components requires a bit more effort. 
There is already a [similar API](https://github.com/GrapesJS/grapesjs/blob/fb5175fd1edd13a2db54d661193fb61a354f8625/src/rich_text_editor/model/RichTextEditor.ts#L414) you can use or re-implement with your own needs (using component definition instead of HTML string)
